[GTA2Radar]
; Main feature switches
; Built-in navigation arrows: 0 = disable, 1 = enable, 2 = dynamic
EnableBuiltinArrows=1
EnablePickupBlips=0
EnablePauseStatsRadar=0

; Gameplay radar settings
RadarBlipsSize=7.0

; Built-in arrow settings
DynamicArrowsDistance = 1.0
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ToggleDefaultArrows = 0x52 

; Pause radar settings
EnablePauseStatsLayout=1
PauseStatsTextY=52
PauseStatsSpriteY=64
PauseRadarLeft=-1
; PauseRadarAutoOffsetX=-256.0
PauseRadarBottom=40.0
PauseRadarWidth=300.0
PauseRadarHeight=300.0
PauseRadarBlipsSize=5.5
PauseRadarRange=100.0
PauseRadarFramePadding=0.25

; Pickup blip settings
EnablePickupIcons=1
EnableVehiclePickupBlips=0
EnableWeaponPickupBlips=1
EnableBonusPickupBlips=1
EnableTokenPickupBlips=1
EnableFrenzyPickupBlips=1
EnableOtherPickupBlips=0
PickupBlipMaxDistance=1.1
PickupIconReferenceSize=30.0

; Diagnostics
EnablePickupBlipLog=0
