[GTA2Radar]
; Main feature switches
; Built-in navigation arrows: 0 = disable, 1 = enable, 2 = dynamic
EnableBuiltinArrows=1
EnablePickupBlips=1
EnablePauseStatsRadar=0

; Gameplay radar settings
RadarBlipsSize=7.0

; Built-in arrow settings
DynamicArrowsDistance = 1.0
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ToggleDefaultArrows = 0x52 

; Pause radar settings
EnablePauseStatsLayout=1
PauseStatsTextY=52
PauseStatsSpriteY=64
PauseRadarLeft=-1
; PauseRadarAutoOffsetX=-256.0
PauseRadarBottom=100.0
PauseRadarWidth=300.0
PauseRadarHeight=300.0
PauseRadarBlipsSize=5.5
PauseRadarRange=100.0
PauseRadarFramePadding=0.25

; Pickup blip settings
EnablePickupIcons=1             # 1 = uses icons for pickups from data\hud\201.dds, 0 = colored markers
EnableVehiclePickupBlips=1      # VAN car with antenna pointing towards level start location (model ID 149)
EnableWeaponPickupBlips=1       # Shows weapon pickups (primarily models IDs 200–223)
EnableBonusPickupBlips=1        # Shows bonuses and power-ups (model IDs 228–240)
EnableTokenPickupBlips=1        # Shows collectible tokens (model ID 266)
EnableFrenzyPickupBlips=1       # Shows the kill-frenzy pickup (model ID 286)
EnableOtherPickupBlips=1        # Shows placed mines (ID 10) and PEW PEW text for bulled projectiles (ID 13, 56, 128, 138, 182, 183, 254, and 265)
PickupBlipMaxDistance=1.1
PickupIconReferenceSize=30.0

; Diagnostics
EnablePickupBlipLog=0
